version: "3.7" 
services:
  # Web service layer
  nginx:
    image: nginx:1.13
    volumes:
      - "./app:/var/www/html"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    expose:
      - 80
    environment:
      VIRTUAL_HOST: dev.localhost
    depends_on:
      - php

  # Application service layer
  php:
    build:
      context: ./php
    volumes:
      - "./app:/var/www/html"

networks:
  default:
    external:
      name: nginx-proxy